name: sonarr
description: Facilitate the communication to and from Sonarr's API, a smart PVR for newsgroup and bittorrent users.
version: 2.0.1
homepage: https://github.com/CometTools/Dart-Packages/tree/master/sonarr
repository: https://github.com/CometTools/Dart-Packages
issue_tracker: https://github.com/CometTools/Dart-Packages/issues
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  dio: ^4.0.0
  intl: ^0.17.0
  json_annotation: ^4.0.1
  meta: ^1.3.0
dev_dependencies:
  build_runner: ^1.12.2
  json_serializable: ^4.1.0
  test: ^1.16.8
scripts:
  build: pub run build_runner build --delete-conflicting-outputs
