name: sonarr_flutter
description: Facilitate the communication to and from Sonarr's API, a smart PVR
  for newsgroup and bittorrent users.
version: 3.0.5
homepage: https://github.com/Not-Dhanraj/sonarr_flutter
repository: https://github.com/Not-Dhanraj/sonarr_flutter
issue_tracker: https://github.com/Not-Dhanraj/sonarr_flutter/issues

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.8.0+1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  meta: ^1.17.0

dev_dependencies:
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  test: ^1.26.2

scripts:
  build: pub run build_runner build --delete-conflicting-outputs
